Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service.name}-user-pool
      AutoVerifiedAttributes:
        - email

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service.name}-TodoTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
