service: graphql-tac-todo

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:DeleteObject"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:BatchGetItem"
            - "dynamodb:BatchWriteItem"
            - "cognito-idp:AdminCreateUser"
            - "cognito-idp:AdminAddUserToGroup"
            - "cognito-idp:AdminRemoveUserFromGroup"
            - "cognito-idp:AdminUpdateUserAttributes"
            - "cognito-idp:AdminGetUser"
          Resource: "*"
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-appsync-simulator
  - serverless-appsync-plugin
  # - serverless-webpack

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      noStart: true
  appSync:
    name: ServerlessAppSyncImmersion
    schema: schema.graphql
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
    mappingTemplatesLocation: mapping-templates

    mappingTemplates:
      - dataSource: DynamoDBTodoTableDS
        type: Query
        field: todos
      - dataSource: DynamoDBTodoTableDS
        type: Query
        field: todo
      - dataSource: DynamoDBTodoTableDS
        type: Mutation
        field: todoCreate
      - dataSource: DynamoDBTodoTableDS
        type: Mutation
        field: todoUpdate
      - dataSource: DynamoDBTodoTableDS
        type: Mutation
        field: todoDelete

    dataSources:
      - type: AMAZON_DYNAMODB
        name: DynamoDBTodoTableDS
        config:
          tableName: !Ref TodoTable

resources: # CloudFormation template syntax
  - ${file(./resources.yml)}
